---
abstract: 'parser for crontab date and time field'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: 0.98
  Time::Local: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Crontab
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Time::Crontab:
    file: lib/Time/Crontab.pm
    version: 0.02
requires:
  List::MoreUtils: 0
  Set::Crontab: 1.03
  perl: 5.008005
resources:
  bugtracker: https://github.com/kazeburo/Time-Crontab/issues
  homepage: https://github.com/kazeburo/Time-Crontab
  repository: git://github.com/kazeburo/Time-Crontab.git
version: 0.02
